#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : PyJWT
Version  : 1.7.1
Release  : 34
URL      : https://files.pythonhosted.org/packages/2f/38/ff37a24c0243c5f45f5798bd120c0f873eeed073994133c084e1cf13b95c/PyJWT-1.7.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/2f/38/ff37a24c0243c5f45f5798bd120c0f873eeed073994133c084e1cf13b95c/PyJWT-1.7.1.tar.gz
Summary  : JSON Web Token implementation in Python
Group    : Development/Tools
License  : MIT
Requires: PyJWT-bin = %{version}-%{release}
Requires: PyJWT-license = %{version}-%{release}
Requires: PyJWT-python = %{version}-%{release}
Requires: PyJWT-python3 = %{version}-%{release}
Requires: cryptography
Requires: flake8
Requires: flake8-import-order
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : pytest-runner
BuildRequires : tox
BuildRequires : virtualenv

%description
=====

%package bin
Summary: bin components for the PyJWT package.
Group: Binaries
Requires: PyJWT-license = %{version}-%{release}

%description bin
bin components for the PyJWT package.


%package license
Summary: license components for the PyJWT package.
Group: Default

%description license
license components for the PyJWT package.


%package python
Summary: python components for the PyJWT package.
Group: Default
Requires: PyJWT-python3 = %{version}-%{release}
Provides: pyjwt-python

%description python
python components for the PyJWT package.


%package python3
Summary: python3 components for the PyJWT package.
Group: Default
Requires: python3-core

%description python3
python3 components for the PyJWT package.


%prep
%setup -q -n PyJWT-1.7.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1544223921
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test || :
%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/PyJWT
cp LICENSE %{buildroot}/usr/share/package-licenses/PyJWT/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pyjwt

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/PyJWT/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
